# Generated by Django 4.2.5 on 2024-04-11 14:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('url', models.CharField(default='', max_length=100)),
            ],
            options={
                'verbose_name': 'Webhook Address',
                'verbose_name_plural': 'Webhook Address',
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='bank_nifty_quantity',
            field=models.PositiveIntegerField(blank=True, default=15, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='bankex_quantity',
            field=models.PositiveIntegerField(blank=True, default=40, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='crudeoil_quantity',
            field=models.PositiveIntegerField(blank=True, default=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='default_quantity',
            field=models.PositiveIntegerField(blank=True, default=10, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='fin_nifty_quantity',
            field=models.PositiveIntegerField(blank=True, default=40, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='nifty_quantity',
            field=models.PositiveIntegerField(blank=True, default=50, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='plan_type',
            field=models.CharField(choices=[('Free', 'Free'), ('Basic', 'Basic -> 10000'), ('Pro', 'Pro -> 15000'), ('VIP', 'VIP -> 20000'), ('Premium', 'Premium -> 30000')], default='Free', max_length=100),
        ),
        migrations.AddField(
            model_name='customuser',
            name='sensex_quantity',
            field=models.PositiveIntegerField(blank=True, default=10, null=True),
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('broker', models.CharField(default='', max_length=50)),
                ('api_name', models.CharField(default='', max_length=50)),
                ('response', models.CharField(default='', max_length=1000)),
                ('response_2', models.CharField(default='', max_length=1000)),
                ('syntax_used', models.CharField(default='', max_length=1000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Response',
                'verbose_name_plural': 'Responses',
            },
        ),
    ]
