# Generated by Django 4.2.5 on 2024-04-11 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_webhook_customuser_bank_nifty_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhook',
            name='address',
            field=models.CharField(default='', max_length=100),
        ),
    ]
