# Generated by Django 4.2.5 on 2024-04-11 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_webhook_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number_or_email', models.CharField(default='', max_length=100)),
                ('subject', models.CharField(default='', max_length=100)),
                ('description', models.TextField(default='', max_length=5000)),
                ('datetime', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Contact Us',
                'verbose_name_plural': 'Contact Us',
            },
        ),
    ]
