# Generated by Django 4.2.5 on 2024-04-11 18:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_contact_us_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='brokers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broker', models.CharField(default='', max_length=100)),
            ],
            options={
                'verbose_name': 'Broker',
                'verbose_name_plural': 'Brokers',
            },
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='', max_length=100)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('segment', models.CharField(choices=[('NSE', 'NSE'), ('BSE', 'BSE'), ('NFO', 'NFO'), ('BFO', 'BFO'), ('MCX', 'MCX')], default='Angel ONE', max_length=100)),
                ('symbol', models.CharField(default='', max_length=100)),
                ('token', models.CharField(default='', max_length=100)),
                ('price', models.CharField(default='0', max_length=100)),
                ('order_type', models.CharField(choices=[('MARKET', 'MARKET'), ('LIMIT', 'LIMIT')], default='MARKET', max_length=100)),
                ('product_type', models.CharField(choices=[('INTRADAY', 'INTRADAY'), ('NRML', 'NRML'), ('CNC', 'CNC')], default='NRML', max_length=100)),
                ('transaction_type', models.CharField(choices=[('BUY', 'BUY'), ('SELL', 'SELL')], default='BUY', max_length=100)),
                ('stoploss', models.CharField(default='0', max_length=100)),
                ('target', models.CharField(default='0', max_length=100)),
                ('brokers', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.brokers')),
                ('url', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.webhook')),
                ('users', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.users')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Order',
            },
        ),
    ]
