# Generated by Django 4.2.5 on 2024-04-11 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_order_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='brokers',
        ),
        migrations.RemoveField(
            model_name='order',
            name='users',
        ),
        migrations.AddField(
            model_name='order',
            name='brokers',
            field=models.ManyToManyField(blank=True, to='dashboard.brokers'),
        ),
        migrations.AddField(
            model_name='order',
            name='users',
            field=models.ManyToManyField(blank=True, to='dashboard.users'),
        ),
    ]
