# Generated by Django 5.0.3 on 2024-04-12 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_remove_order_brokers_remove_order_users_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterField(
            model_name='order',
            name='segment',
            field=models.CharField(choices=[('NSE', 'NSE'), ('BSE', 'BSE'), ('NFO', 'NFO'), ('BFO', 'BFO'), ('MCX', 'MCX')], default='NSE', max_length=100),
        ),
    ]
