# Generated by Django 4.2.5 on 2024-05-28 11:02

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text'),
        ),
    ]
