# Generated by Django 4.2.5 on 2024-05-28 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_alter_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='keywords',
            field=models.CharField(default='Nyaksha', max_length=250),
        ),
    ]
