# Generated by Django 4.2.5 on 2024-04-11 11:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='angel_api',
            fields=[
                ('apiid', models.AutoField(primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('api_name', models.CharField(default='', max_length=100)),
                ('api_key', models.CharField(default='', max_length=100)),
                ('client_id', models.CharField(default='', max_length=100)),
                ('password', models.CharField(default='', max_length=100)),
                ('t_otp_token', models.CharField(default='', max_length=100)),
                ('is_trading', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Angel ONE API',
                'verbose_name_plural': 'Angel ONE API',
            },
        ),
    ]
