# Generated by Django 4.2.5 on 2024-04-11 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='angel_api',
            old_name='apiid',
            new_name='id',
        ),
    ]
