# Generated by Django 4.2.5 on 2024-04-11 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_rename_apiid_angel_api_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='angel_api',
            old_name='password',
            new_name='m_pin',
        ),
    ]
