# Generated by Django 4.2.5 on 2024-04-11 17:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apis', '0003_rename_password_angel_api_m_pin'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='angel_api',
            unique_together={('api_name', 'api_key', 'client_id', 'm_pin', 't_otp_token'), ('client_id', 'm_pin', 't_otp_token'), ('user', 'api_name')},
        ),
    ]
