# Generated by Django 4.2.5 on 2024-04-17 17:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apis', '0004_alter_angel_api_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='dhan_api',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('api_name', models.CharField(default='', max_length=100)),
                ('client_id', models.CharField(default='', max_length=100)),
                ('access_token', models.CharField(default='', max_length=500)),
                ('is_trading', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dhan HQ API',
                'verbose_name_plural': 'Dhan HQ API',
                'unique_together': {('client_id', 'access_token'), ('user', 'api_name'), ('api_name', 'client_id', 'access_token')},
            },
        ),
    ]
