# Generated by Django 4.2.5 on 2024-04-17 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0005_dhan_api'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dhan_api',
            name='access_token',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
